version: "3.9"

services:
  ui:
    build:
      context: ./browser
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./browser/src:/usr/app/src
      - /ui/src/node_modules
    networks:
      - net-photo-album
  proxy-server:
    build:
      context: ./proxy-server
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - net-photo-album
networks:
  net-photo-album:
    name: net-photo-album
