version: "3.9"

services:
  ui:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./src:/usr/app/src
      - /ui/src/node_modules
    networks:
      - net-portfolio
networks:
  net-portfolio:
    name: net-portfolio
